version: "3.6"

services: 
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
     image: postgres
     restart: always
     ports:
       - "15432:5432"
     volumes:
       - "./data:/var/lib/postgresql/data"
     environment:
       POSTGRES_PASSWORD: "postgres"
  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@teste.com.br"
      PGADMIN_DEFAULT_PASSWORD: "testeadailson"
    ports:
      - "16543:80"
    depends_on:
      -  db

